on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
 

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: build-publish
        uses: bitovi/github-actions-react-to-ghp@v1.2.0
        with:
          path: build
      # - name: Setup Pages 
      #   uses: actions/configure-pages@v2
      # - name: Setup Node Environment
      #   uses: actions/setup-node@v3
      #   with: 
      #     node-version-file: .nvmrc
      #     cache: "npm"
          
      # - name: Build 
      #   uses: npm run build 
      # - name: Deploy 
      #   uses: node_modules/.bin/gh-pages -b 